name: TechInterview

services:
  Postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: interview
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
